"""initial persistence schema

Revision ID: 0b5123afcf23
Revises:
Create Date: 2026-07-29 10:03:53.554597
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0b5123afcf23"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_service", sa.String(length=32), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_events_actor_user_id"), "audit_events", ["actor_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_events_owner_id"), "audit_events", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_resource_id"), "audit_events", ["resource_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_trace_id"), "audit_events", ["trace_id"], unique=False)
    op.create_table(
        "courses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_courses_owner_id"), "courses", ["owner_id"], unique=False)
    op.create_table(
        "classrooms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "analysis_contract",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_classrooms_course_id"), "classrooms", ["course_id"], unique=False)
    op.create_index(op.f("ix_classrooms_owner_id"), "classrooms", ["owner_id"], unique=False)
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("classroom_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("upload_status", sa.String(length=32), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("etag", sa.String(length=255), nullable=True),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("size_bytes > 0", name="ck_assets_size_positive"),
        sa.ForeignKeyConstraint(["classroom_id"], ["classrooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    op.create_index(op.f("ix_assets_classroom_id"), "assets", ["classroom_id"], unique=False)
    op.create_index(op.f("ix_assets_owner_id"), "assets", ["owner_id"], unique=False)
    op.create_table(
        "processing_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("classroom_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("privacy_mode", sa.String(length=16), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column(
            "analysis_contract",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("progress >= 0 AND progress <= 1", name="ck_tasks_progress_range"),
        sa.CheckConstraint("retry_count >= 0", name="ck_tasks_retry_nonnegative"),
        sa.ForeignKeyConstraint(["classroom_id"], ["classrooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processing_tasks_classroom_id"), "processing_tasks", ["classroom_id"], unique=False
    )
    op.create_index(
        op.f("ix_processing_tasks_lease_expires_at"),
        "processing_tasks",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_processing_tasks_owner_id"), "processing_tasks", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_processing_tasks_stage"), "processing_tasks", ["stage"], unique=False)
    op.create_index(
        op.f("ix_processing_tasks_status"), "processing_tasks", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_processing_tasks_trace_id"), "processing_tasks", ["trace_id"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("classroom_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), server_default="", nullable=False),
        sa.Column("export_object_key", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["classroom_id"], ["classrooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("classroom_id", name="uq_reports_classroom"),
    )
    op.create_index(op.f("ix_reports_classroom_id"), "reports", ["classroom_id"], unique=False)
    op.create_index(op.f("ix_reports_owner_id"), "reports", ["owner_id"], unique=False)
    op.create_table(
        "analysis_conclusions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("classroom_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("reviewed_content", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("skill", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["classroom_id"], ["classrooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["processing_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_conclusions_classroom_id"),
        "analysis_conclusions",
        ["classroom_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_conclusions_owner_id"), "analysis_conclusions", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_conclusions_review_status"),
        "analysis_conclusions",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_conclusions_task_id"), "analysis_conclusions", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_conclusions_trace_id"), "analysis_conclusions", ["trace_id"], unique=False
    )
    op.create_table(
        "task_assets",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["processing_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id", "asset_id"),
    )
    op.create_table(
        "task_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("trace_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("progress >= 0 AND progress <= 1", name="ck_task_events_progress_range"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["processing_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_events_created_at"), "task_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_task_events_owner_id"), "task_events", ["owner_id"], unique=False)
    op.create_index(op.f("ix_task_events_task_id"), "task_events", ["task_id"], unique=False)
    op.create_index(op.f("ix_task_events_trace_id"), "task_events", ["trace_id"], unique=False)
    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("speaker", sa.String(length=64), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source_language", sa.String(length=16), nullable=False),
        sa.Column("translation", sa.Text(), nullable=True),
        sa.Column("translation_language", sa.String(length=16), nullable=True),
        sa.Column("is_edited", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("start_ms >= 0 AND end_ms > start_ms", name="ck_transcript_valid_range"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["processing_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "index", name="uq_transcript_task_index"),
    )
    op.create_index(
        op.f("ix_transcript_segments_owner_id"), "transcript_segments", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_transcript_segments_task_id"), "transcript_segments", ["task_id"], unique=False
    )
    op.create_table(
        "evidence_references",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("conclusion_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=True),
        sa.Column("segment_id", sa.UUID(), nullable=True),
        sa.Column("start_ms", sa.Integer(), nullable=True),
        sa.Column("end_ms", sa.Integer(), nullable=True),
        sa.Column("page_no", sa.Integer(), nullable=True),
        sa.Column("image_ref", sa.String(length=512), nullable=True),
        sa.Column("quote", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["conclusion_id"], ["analysis_conclusions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["segment_id"], ["transcript_segments.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_references_conclusion_id"),
        "evidence_references",
        ["conclusion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_references_owner_id"), "evidence_references", ["owner_id"], unique=False
    )
    op.create_table(
        "report_conclusions",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("conclusion_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conclusion_id"], ["analysis_conclusions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("report_id", "conclusion_id"),
    )
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("conclusion_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("resulting_status", sa.String(length=32), nullable=False),
        sa.Column("previous_content", sa.Text(), nullable=True),
        sa.Column("edited_content", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("decided_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conclusion_id"], ["analysis_conclusions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["decided_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_decisions_conclusion_id"),
        "review_decisions",
        ["conclusion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_decisions_owner_id"), "review_decisions", ["owner_id"], unique=False
    )
    op.create_table(
        "transcript_segment_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("segment_id", sa.UUID(), nullable=False),
        sa.Column("previous_text", sa.Text(), nullable=True),
        sa.Column("previous_speaker", sa.String(length=64), nullable=True),
        sa.Column("previous_translation", sa.Text(), nullable=True),
        sa.Column("edited_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["edited_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["segment_id"], ["transcript_segments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transcript_segment_revisions_owner_id"),
        "transcript_segment_revisions",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcript_segment_revisions_segment_id"),
        "transcript_segment_revisions",
        ["segment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transcript_segment_revisions_segment_id"),
        table_name="transcript_segment_revisions",
    )
    op.drop_index(
        op.f("ix_transcript_segment_revisions_owner_id"), table_name="transcript_segment_revisions"
    )
    op.drop_table("transcript_segment_revisions")
    op.drop_index(op.f("ix_review_decisions_owner_id"), table_name="review_decisions")
    op.drop_index(op.f("ix_review_decisions_conclusion_id"), table_name="review_decisions")
    op.drop_table("review_decisions")
    op.drop_table("report_conclusions")
    op.drop_index(op.f("ix_evidence_references_owner_id"), table_name="evidence_references")
    op.drop_index(op.f("ix_evidence_references_conclusion_id"), table_name="evidence_references")
    op.drop_table("evidence_references")
    op.drop_index(op.f("ix_transcript_segments_task_id"), table_name="transcript_segments")
    op.drop_index(op.f("ix_transcript_segments_owner_id"), table_name="transcript_segments")
    op.drop_table("transcript_segments")
    op.drop_index(op.f("ix_task_events_trace_id"), table_name="task_events")
    op.drop_index(op.f("ix_task_events_task_id"), table_name="task_events")
    op.drop_index(op.f("ix_task_events_owner_id"), table_name="task_events")
    op.drop_index(op.f("ix_task_events_created_at"), table_name="task_events")
    op.drop_table("task_events")
    op.drop_table("task_assets")
    op.drop_index(op.f("ix_analysis_conclusions_trace_id"), table_name="analysis_conclusions")
    op.drop_index(op.f("ix_analysis_conclusions_task_id"), table_name="analysis_conclusions")
    op.drop_index(op.f("ix_analysis_conclusions_review_status"), table_name="analysis_conclusions")
    op.drop_index(op.f("ix_analysis_conclusions_owner_id"), table_name="analysis_conclusions")
    op.drop_index(op.f("ix_analysis_conclusions_classroom_id"), table_name="analysis_conclusions")
    op.drop_table("analysis_conclusions")
    op.drop_index(op.f("ix_reports_owner_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_classroom_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_processing_tasks_trace_id"), table_name="processing_tasks")
    op.drop_index(op.f("ix_processing_tasks_status"), table_name="processing_tasks")
    op.drop_index(op.f("ix_processing_tasks_stage"), table_name="processing_tasks")
    op.drop_index(op.f("ix_processing_tasks_owner_id"), table_name="processing_tasks")
    op.drop_index(op.f("ix_processing_tasks_lease_expires_at"), table_name="processing_tasks")
    op.drop_index(op.f("ix_processing_tasks_classroom_id"), table_name="processing_tasks")
    op.drop_table("processing_tasks")
    op.drop_index(op.f("ix_assets_owner_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_classroom_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_classrooms_owner_id"), table_name="classrooms")
    op.drop_index(op.f("ix_classrooms_course_id"), table_name="classrooms")
    op.drop_table("classrooms")
    op.drop_index(op.f("ix_courses_owner_id"), table_name="courses")
    op.drop_table("courses")
    op.drop_index(op.f("ix_audit_events_trace_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_resource_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_owner_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_user_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
